# Site settings
title: Souvik "SG" Ghosh
email: souvik.ghosh@case.edu
url: https://example.github.io
description: "Academic Website of chemical/mechanical engineer SG Ghosh"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Souvik "SG" Ghosh

# Social networks usernames 
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
